name: Update Index

on:
  push:

jobs:
  run-script:
    name: Run Python Script
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9  # Replace with the desired Python version (e.g., 3.8)

    - name: Run generate-index.py
      run: python generate-index.py  # Replace with the command to run your Python script

    - name: Check for changes
      id: check_changes
      run: |
        git diff --quiet || echo "::set-output name=changes::true"
      
    - name: Commit and push changes
      if: steps.check_changes.outputs.changes == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "feat(README): Update repository index"
        git push

